name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Build Chrome Extension
        run: npm run build

      # https://github.com/microsoft/playwright/issues/7249#issuecomment-2664215505
      - name: Extract Playwright version
        shell: bash
        run: echo "PLAYWRIGHT_VERSION=$(jq -r '.devDependencies.playwright' package.json)" >> $GITHUB_ENV

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14

      - name: Upload build file
        uses: actions/upload-artifact@v4
        with:
          name: chrome.zip
          path: dist/chrome.zip
          retention-days: 14

      # - name: Upload metafile
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Meta files
      #     path: |
      #       dist/meta.json
      #       dist/content-script-meta.json
      #     retention-days: 14

      - name: Build Firefox Extension
        run: npm run build:firefox

      - name: Upload build file
        uses: actions/upload-artifact@v4
        with:
          name: firefox.zip
          path: dist/firefox.xpi
          retention-days: 14
